# Mac workflow. Adapted from the Ubuntu one.

name: Mac latest
on:
#  push:
#    branches: [ "main" ]
#    paths-ignore:
#      - 'docs/**'
#      - 'README**'
#  pull_request:
#    branches: [ "main" ]
# If not the above, then:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  call-workflow-passing-data:
    uses: ABRG-Models/morphologica/.github/workflows/cmake-mac-template.yml@main
    with:
      CONTAINER_IMAGE: macos-latest
      BUILD_TYPE: Release
      CC: clang-15
      CXX: clang++-15
