name: Ubuntu 24.04
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'README**'
      - 'examples/screenshots/**'
      - 'examples/docs/**'
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow-passing-data:
    uses: ABRG-Models/morphologica/.github/workflows/cmake-ubuntu-template.yml@457-add-qt-wx-to-ci
    with:
      RUNNER_IMAGE: ubuntu-24.04
      BUILD_TYPE: Release
      CC: gcc-13
      CXX: g++-13
