name: Ubu 24 clang18
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'README**'
  pull_request:
    branches: [ "main" ]

jobs:
  call-workflow-passing-data:
    uses: ABRG-Models/morphologica/.github/workflows/cmake-ubuntu-template.yml@feat/github_actions_improvments
    with:
      RUNNER_IMAGE: ubuntu-24.04
      BUILD_TYPE: Release
      CC: clang-18
      CXX: clang++-18
